apiVersion: v2
name: db-postgres-member-mgmt
description: A Helm chart for PostgreSQL database for Member Management Service
type: application
version: 0.1.0
appVersion: "18.2.0"
keywords:
  - member-mgmt-db
dependencies:
  - name: postgresql
    version: "18.2.3"
    repository: "oci://registry-1.docker.io/bitnamicharts"