apiVersion: v1
kind: Secret
metadata:
  name: postgres-default-secret
  namespace: default
type: Opaque
data:
  postgres-password: {{ .Values.rootPassword | b64enc }}
  appointment-mgmt-password: {{ .Values.appointmentDbPassword | b64enc }}
  member-mgmt-password: {{ .Values.memberDbPassword | b64enc }}
  notification-mgmt-password: {{ .Values.notificationDbPassword | b64enc }}